### ISSUE TITLE
Library don't compliances to IPC-7351

### ISSUE THREAD

**Issue by eldarkg** [KiCad/Capacitors_Tantalum_SMD.pretty#6]
- [ ] pin 1 (positive) should be on left side
- [ ] keys placed on pads in some parts
- [ ] no courtyard

For e.g. TantalC_SizeU_EIA-6032.kicad_mod.
After production PCB boards keys will dissapear

**Comment by SchrodingersGat** [comment]
Hey @eldarkg I have addressed these all here - https://github.com/KiCad/Capacitors_Tantalum_SMD.pretty/pull/8

Please let me know if you think I have missed anything!
