### ISSUE TITLE
*_Reflow footprints do not have a polarity marker

### ISSUE THREAD

**Issue by mrnuke** [KiCad/Capacitors_Tantalum_SMD.pretty#7]
I suspect the intent was that these footprints would only be used with pick and place machines, so that the polarity marker was assumed to be redundant. Unfortunately the fallacy of that assumption is very apparent when reworking boards, or even when manually placing components over solder paste. Luckily, I have not, to date, installed a capacitor in reverse.

I realize that the soldermask lines should be longer in one direction, but that is neither obvious, nor easily visible.

I have yet to blow up a tantalum capacitor because of this, but I believe this issue should be addressed for the following reasons:
- polarity markers are, in fact, useful
- consistency with the other footprints in the library

**Comment by SchrodingersGat** [comment]
Hmm these footprints need a *LOT* of work, by the looks of things. I shall have a go at improving them and also including the fixes required in https://github.com/KiCad/Capacitors_Tantalum_SMD.pretty/issues/6

**Comment by SchrodingersGat** [comment]
@mrnuke  check out the new PR here - https://github.com/KiCad/Capacitors_Tantalum_SMD.pretty/pull/8

Hopefully it will be merged soon - let me know now if you want anything else added to the script :)

**Comment by mrnuke** [comment]
@SchrodingersGat, I believe the pin 1 indicator should be more prominent than a simple extended line. As evidenced in [this github issue](https://github.com/KiCad/Housings_SSOP.pretty/issues/15), soldermask lines may be removed by the manufacturer when they overlap with exposed soldermask. What can happen with these simple longer lines is that they may end up getting trimmed at the manufacturing stage, in which brings us back to the original issue.

These are some example silkscreen marking which may alleviate the issue:

![tantal_ex_1](https://cloud.githubusercontent.com/assets/2610559/17636214/b4e9a9b6-6090-11e6-8701-f6aab681e13d.png)
![tantal_ex_2](https://cloud.githubusercontent.com/assets/2610559/17636213/b4e9949e-6090-11e6-9a54-6182880ebfe9.png)
![tantal_ex_3](https://cloud.githubusercontent.com/assets/2610559/17636215/b4ea25b2-6090-11e6-8ff7-0ea256707c7f.png)
![tantal_ex_4](https://cloud.githubusercontent.com/assets/2610559/17636216/b4ee45b6-6090-11e6-8a1e-606406a196e7.png)

**Comment by SchrodingersGat** [comment]
Ok good point, thanks. I'll update the script accordingly.

**Comment by SchrodingersGat** [comment]
It has been improved as follows:

![eg](https://cloud.githubusercontent.com/assets/10080325/17641914/338758a0-6176-11e6-863b-79226cf8cc86.png)

**Comment by mrnuke** [comment]
Hi Oliver. Thank you very much for addressing this issue so promptly. On paper, this looks like it will work nicely. I am going to have a test PCB manufactured with the updated footprints. I'll use Oshpark for this test, as they're much faster than Asian manufacturers. I suspect this will turn out quite nicely.

**Comment by SchrodingersGat** [comment]
PR has been merged, closing
