### ISSUE TITLE
Why TantalC_SizeR_EIA-2012 pads are so large?

### ISSUE THREAD

**Issue by oliviermartin** [KiCad/Capacitors_Tantalum_SMD.pretty#9]
Hi all,
I have only been using `TantalC_SizeR_EIA-2012.kicad_mod` from this footprint library for this tantalum capacitor: http://datasheets.avx.com/TAJ_LOW_PROFILE.pdf

As the silkscreen shows, the pads are much larger than the component itself:
![tantalc](https://cloud.githubusercontent.com/assets/5757507/20097904/284f9c66-a5b1-11e6-8404-bd14929f1392.png)

Is there any reason behind these large pads?

**Comment by SchrodingersGat** [comment]
@oliviermartin the footprints in this library have now been updated - do they look OK to you now?

**Comment by evanshultz** [comment]
@oliviermartin Please let us know if your issue is closed and, if so, please close this issue. Thank you!

**Comment by poeschlr** [comment]
New footprints conforming to IPC have been created in the new repo.
This repo is now a legacy repo. 
Replacement repo: https://github.com/KiCad/kicad-footprints

If the footprints are still not ok for you please open a new issue over at the new repo.
